rabbit: bin/rabbitmq-server
rceleryd: bin/rceleryd --tasks tasks --vhost=$RCELERY_VHOST --host=$RCELERY_HOST --port=$RCELERY_PORT --application integration --workers 4 -c $RCELERY_AUTO_RECOVERY
celeryd: bin/celeryd -Q rcelery.python.integration

